from __future__ import annotations

DEFAULT_CAMERA_COLOR_PALETTE = (
    "#2563eb",
    "#059669",
    "#d97706",
    "#dc2626",
    "#7c3aed",
    "#0f766e",
)

DEFAULT_DETECTOR_MODEL_PATH = "models/yolo26m.pt"
DEFAULT_DETECTOR_CONFIDENCE = 0.18
DEFAULT_DETECTOR_INFERENCE_SIZE = 736
DEFAULT_DETECTOR_AUGMENTATION = False

DEFAULT_TRACKER_BACKEND = "botsort"
DEFAULT_TRACKER_PERSIST = True
DEFAULT_TRACKER_REID_ENABLED = True
DEFAULT_TRACKER_TRACK_BUFFER = 16
DEFAULT_TRACKER_MATCH_THRESH = 0.75
DEFAULT_TRACKER_NEW_TRACK_THRESH = 0.35
DEFAULT_TRACKER_PROXIMITY_THRESH = 0.6
DEFAULT_TRACKER_APPEARANCE_THRESH = 0.2
DEFAULT_TRACK_TIMEOUT_S = 1.20
DEFAULT_TRACKER_MAX_MISSED_FRAMES = 10
DEFAULT_BBOX_PUBLISH_TTL_S = 0.15
DEFAULT_TRACKER_MAX_WORLD_DISTANCE_M = 0.5
DEFAULT_TRACKER_MAX_IMAGE_DISTANCE_PX = 85.0
DEFAULT_TRACKER_MIN_IOU = 0.08
DEFAULT_TRACKER_ANCHOR_WEIGHT = 0.65
DEFAULT_TRACKER_IOU_WEIGHT = 0.25
DEFAULT_TRACKER_CONFIDENCE_WEIGHT = 0.05

DEFAULT_REID_ENABLED = True
DEFAULT_REID_BACKEND = "torchreid_osnet"
DEFAULT_REID_MODEL_NAME = "osnet_x1_0"
DEFAULT_REID_WEIGHTS_PATH = "models/reid/osnet_x1_0_msmt17.pth"
DEFAULT_REID_WEIGHTS_URL = (
    "https://huggingface.co/kaiyangzhou/osnet/resolve/main/"
    "osnet_x1_0_msmt17_combineall_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip_jitter.pth"
)
DEFAULT_REID_DOWNLOAD_IF_MISSING = True
DEFAULT_REID_MIN_BBOX_HEIGHT_PX = 96
DEFAULT_REID_MIN_CONFIDENCE = 0.45
DEFAULT_REID_OVERLAP_MIN_BBOX_HEIGHT_PX = 72
DEFAULT_REID_OVERLAP_MIN_CONFIDENCE = 0.35
DEFAULT_REID_EMBEDDING_SIMILARITY_THRESHOLD = 0.72
DEFAULT_REID_SINGLE_CAMERA_RESTITCH_THRESHOLD = 0.68
DEFAULT_REID_CROSS_CAMERA_MATCH_THRESHOLD = 0.74
DEFAULT_REID_EMBEDDING_MOMENTUM = 0.85
DEFAULT_REID_MAX_EMBEDDING_MEMORY = 30
DEFAULT_REID_GALLERY_SIZE_PER_CAMERA = 30
DEFAULT_REID_GALLERY_SIZE_GLOBAL = 60
DEFAULT_REID_MATCH_TOPK = 5
DEFAULT_REID_MATCH_REDUCE = "mean_top3"
DEFAULT_REID_RERANK_ENABLED = False
DEFAULT_REID_INPUT_WIDTH = 128
DEFAULT_REID_INPUT_HEIGHT = 256
DEFAULT_REID_INPUT_MEAN = [0.485, 0.456, 0.406]
DEFAULT_REID_INPUT_STD = [0.229, 0.224, 0.225]

DEFAULT_IDENTITY_RESTITCH_ENABLED = True
DEFAULT_IDENTITY_MAX_GAP_S = 2.0
DEFAULT_IDENTITY_BASE_DISTANCE_M = 0.8
DEFAULT_IDENTITY_SPEED_M_PER_S = 1.0
DEFAULT_IDENTITY_RESTITCH_THRESHOLD = 0.68
DEFAULT_IDENTITY_CONFIRMATION_FRAMES = 3
DEFAULT_IDENTITY_LOST_TRACK_RETENTION_S = 1.20

DEFAULT_ZONE_ENTRY_MIN_DURATION_S = 0.35
DEFAULT_ZONE_EXIT_GRACE_S = 0.75
DEFAULT_UI_LIVE_SNAPSHOT_RATE_HZ = 4.0
DEFAULT_OPERATOR_PREVIEW_FPS = 12.0
DEFAULT_HEATMAP_ENABLED = True
DEFAULT_HEATMAP_SAMPLE_INTERVAL_S = 0.5
DEFAULT_HEATMAP_GRID_COLUMNS = 160
DEFAULT_HEATMAP_MIN_ROWS = 40
DEFAULT_HEATMAP_MAX_ROWS = 160

DEFAULT_OVERLAP_DEDUP_ENABLED = True
DEFAULT_OVERLAP_AREA_MIN_M2 = 0.5
DEFAULT_OVERLAP_BOUNDARY_GAP_M = 1.2
DEFAULT_OVERLAP_MAX_DISTANCE_M = 1.0
DEFAULT_OVERLAP_MAX_TIME_GAP_S = 1.0
DEFAULT_OVERLAP_APPEARANCE_WEIGHT = 0.50
DEFAULT_OVERLAP_WORLD_WEIGHT = 0.30
DEFAULT_OVERLAP_TIMING_WEIGHT = 0.15
DEFAULT_OVERLAP_GEOMETRY_WEIGHT = 0.05
DEFAULT_OVERLAP_SIMILARITY_THRESHOLD = 0.74
DEFAULT_OVERLAP_MARGIN_MIN = 0.08
DEFAULT_OVERLAP_CONFIRMATION_FRAMES = 3

DEFAULT_MAP_DEDUP_ENABLED = True
DEFAULT_MAP_OVERLAP_BOUNDARY_BUFFER_M = 0.50
DEFAULT_MAP_MAX_DISTANCE_M = 0.80
DEFAULT_MAP_MAX_TIME_GAP_S = 0.25
DEFAULT_MAP_SIMILARITY_THRESHOLD = 0.60
DEFAULT_MAP_MARGIN_MIN = 0.05
DEFAULT_MAP_CONFIRMATION_FRAMES = 2
DEFAULT_MAP_WORLD_ALIGNMENT_WEIGHT = 0.55
DEFAULT_MAP_OVERLAP_MEMBERSHIP_WEIGHT = 0.20
DEFAULT_MAP_TIMING_WEIGHT = 0.20
DEFAULT_MAP_APPEARANCE_WEIGHT = 0.15
DEFAULT_MAP_MOTION_WEIGHT = 0.10
DEFAULT_MAP_TRACKLET_WINDOW_S = 0.20
DEFAULT_MAP_TRACKLET_MIN_POINTS = 2
DEFAULT_MAP_TRACKLET_KEEPALIVE_S = 0.40
DEFAULT_MAP_BATCH_WINDOW_S = 0.20
DEFAULT_MAP_BATCH_STEP_S = 0.10
DEFAULT_MAP_PRESENCE_HOLD_S = 0.30
DEFAULT_MAP_PRESENCE_REASSIGN_WINDOW_S = 0.50
DEFAULT_MAP_PRESENCE_PUBLISH_TTL_S = 0.25
DEFAULT_MAP_MAX_EXACT_ASSIGNMENT_SIZE = 8

DEFAULT_PLAYBACK_SYNC_ENABLED_FOR_FILE_SOURCES = True
DEFAULT_PLAYBACK_SYNC_TARGET_FPS = 30.0
DEFAULT_PLAYBACK_SYNC_TOLERANCE_S = 0.040
DEFAULT_PLAYBACK_LATE_FRAME_DROP_THRESHOLD_S = 0.120
DEFAULT_PLAYBACK_STALE_PACKET_THRESHOLD_S = 0.150
DEFAULT_PLAYBACK_CAMERA_MISSING_TIMEOUT_S = 0.500
DEFAULT_PLAYBACK_MAX_BUFFERED_PACKETS_PER_CAMERA = 12

DEFAULT_DISTRIBUTED_ENABLED = False
DEFAULT_DISTRIBUTED_BIND_HOST = "0.0.0.0"
DEFAULT_DISTRIBUTED_PORT = 6100
DEFAULT_DISTRIBUTED_PREVIEW_FPS = 12.0
DEFAULT_DISTRIBUTED_PREVIEW_JPEG_QUALITY = 80
DEFAULT_DISTRIBUTED_PREVIEW_MAX_WIDTH = 1280
DEFAULT_DISTRIBUTED_HEARTBEAT_INTERVAL_S = 1.0
DEFAULT_DISTRIBUTED_WORKER_TIMEOUT_S = 4.0
DEFAULT_DISTRIBUTED_SOCKET_IO_TIMEOUT_S = 5.0
DEFAULT_DISTRIBUTED_SERVER_PROCESS_FPS = 15.0
DEFAULT_DISTRIBUTED_PROTOCOL_VERSION = "1.0"
